### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by zhangfq-chemistry** [iceprincefounder/ZeldaEngine#2]
/home/zhangfq/projects/ZeldaEngine/Engine/ZeldaEngine/ZeldaEngine.cpp: In static member function ‘static void XkShaderCompiler::ReadShaderFile(std::vector<unsigned char>&, VkShaderStageFlagBits&, const XkString&)’:
/home/zhangfq/projects/ZeldaEngine/Engine/ZeldaEngine/ZeldaEngine.cpp:152:42: error: ‘VK_SHADER_STAGE_MESH_BIT_EXT’ was not declared in this scope; did you mean ‘VK_SHADER_STAGE_MESH_BIT_NV’?
  152 |                         outShaderStage = VK_SHADER_STAGE_MESH_BIT_EXT;
      |                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                          VK_SHADER_STAGE_MESH_BIT_NV
/home/zhangfq/projects/ZeldaEngine/Engine/ZeldaEngine/ZeldaEngine.cpp:154:42: error: ‘VK_SHADER_STAGE_TASK_BIT_EXT’ was not declared in this scope; did you mean ‘VK_SHADER_STAGE_TASK_BIT_NV’?
  154 |                         outShaderStage = VK_SHADER_STAGE_TASK_BIT_EXT;
      |                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                          VK_SHADER_STAGE_TASK_BIT_NV
/home/zhangfq/projects/ZeldaEngine/Engine/ZeldaEngine/ZeldaEngine.cpp: In lambda function:
/home/zhangfq/projects/ZeldaEngine/Engine/ZeldaEngine/ZeldaEngine.cpp:265:30: error: ‘VK_SHADER_STAGE_MESH_BIT_EXT’ was not declared in this scope; did you mean ‘VK_SHADER_STAGE_MESH_BIT_NV’?
  265 |                         case VK_SHADER_STAGE_MESH_BIT_EXT:
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                              VK_SHADER_STAGE_MESH_BIT_NV
/home/zhangfq/projects/ZeldaEngine/Engine/ZeldaEngine/ZeldaEngine.cpp:267:30: error: ‘VK_SHADER_STAGE_TASK_BIT_EXT’ was not declared in this scope; did you mean ‘VK_SHADER_STAGE_TASK_BIT_NV’?
  267 |                         case VK_SHADER_STAGE_TASK_BIT_EXT:
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by iceprincefounder** [comment]
Hi dude, linux is not tesed, try windows or macOS, and also change VK_SHADER_STAGE_TASK_BIT_EXT to VK_SHADER_STAGE_MESH_BIT_NV when you use nividia GPU, it might fix your problem~
